
backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "site.json"
        label: "Main Content"
        name: "sitejson"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Tagline", name: "hero_tagline", widget: "text" }
          - { label: "Badges", name: "badges", widget: "list", field: {label: "Badge", name: "badge", widget: "string"} }
          - { label: "Services Intro", name: "services_intro", widget: "string" }
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "desc", widget: "text"}
          - { label: "About Text", name: "about_text", widget: "text" }
          - { label: "Work Intro", name: "work_intro", widget: "string" }
          - label: "Work Items"
            name: "work"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "desc", widget: "text"}
          - { label: "Contact Email", name: "contact_email", widget: "string" }
          - { label: "Contact Copy", name: "contact_copy", widget: "text" }
